language: node_js

node_js:
  - "lts/*"

cache:
  directories:
    - "node_modules"

install:
  - npm -v
  - node -v
  - npm ci

script:
  - npm run build

deploy:
  - provider: script
    skip_cleanup: true
    script: npm run release
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script: npm run release
    on:
      branch: beta

notifications:
  email:
    on_success: never
